export const workingHours = [
    { userName: "Aman Kumar", workday: 19 },
    { userName: "Aristotle Diogo Fernandes", workday: 21 },
    { userName: "Mohammed Rizwan", workday: 23 },
    { userName: "Narahari Mengane", workday: 0 },
    { userName: "Nikita Dehariya", workday: 0 },
    { userName: "Parikshit Taksande", workday: 21 },
    { userName: "Sandeep Malakar", workday: 21 },
    { userName: "Sandeep Kumar Maurya", workday: 23 },
    { userName: "Satish Gogiya", workday: 21 },
    { userName: "Tarun Sharma", workday: 0 },
    { userName: "Krisnaraj K.C", workday: 22 },
    { userName: "Pradap V", workday: 21 },
    { userName: "Atharva Nevase", workday: 11 },
]